//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserRole
    {
        public string UniqueID { get; set; }
        public string UsersUniqueID { get; set; }
        public string RolesUniqueID { get; set; }
    }
}
