//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XXGLEntities : DbContext
    {
        public XXGLEntities()
            : base("name=XXGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LnkOperationsLanguages> LnkOperationsLanguages { get; set; }
        public virtual DbSet<LnkRolesWebFunctions> LnkRolesWebFunctions { get; set; }
        public virtual DbSet<LnkUsersRoles> LnkUsersRoles { get; set; }
        public virtual DbSet<LnkWebFunctionsLanguages> LnkWebFunctionsLanguages { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WebFunctions> WebFunctions { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
    }
}
